const ffmpeg = require('fluent-ffmpeg')

const command = ffmpeg('/dev/video0')
    .inputFormat('v4l2')
    .inputFPS(25)
    .output('http://localhost:7688/yo')
    .format('mpegts')
    .videoCodec('mpeg1video')
    .size('640x480')
    .videoBitrate('1000k')
    .outputOptions('-bf 0')
    .output('output.jpg')
    //.outputOptions(['-f image2','-vf fps=1/5'])
    .outputOptions(['-update 1','-r 1'])
    .run()
