const ffmpeg = require('fluent-ffmpeg')

const command = ffmpeg('/dev/video0')
    .inputFormat('v4l2')
    .inputFPS(25)
    .format('mpegts')
    .videoCodec('mpeg1video')
    .size('640x480')
    .videoBitrate('1000k')
    .outputOptions('-bf 0')
    .save('http://localhost:7688/yo')
